config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to User Auth!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "UserAuth"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    Made |
    by #{ link_to "Harshdeep Kanhai", "https://harshdeepkanhai.github.io/" } |
  %nav
    %ul
      %li
        = link_to "About", about_path
      %li
        = link_to "Contact", contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "User Auth", root_path, id: "logo"
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Home", root_path
        %li
          = link_to "Help", help_path
        - if logged_in?
          %li
            = link_to "Users", users_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              Account
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to "Profile", current_user
              %li
                = link_to "Settings", edit_user_path(current_user)
              %li.divider
              %li
                = link_to "Log out", logout_path, method: :delete
        - else
          %li
            = link_to "Log in", login_path

app/views/layouts/_rails_default.html.haml
= csrf_meta_tags
= csp_meta_tag

= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  %script{ :src => '//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js' }

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title #{ full_title(yield(:title)) }
    = render 'layouts/rails_default'
    = render 'layouts/shim'
  %body
    =render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        %div(class="alert alert-#{message_type}")= message
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{ pluralize(@user.errors.count, "error") }
    %ul
    - @user.errors.full_messages.each do |msg|
      %li= msg

app/views/static_pages/about.html.haml
= provide(:title, "About")
%h1 About
%ul
  %li This site User Auth helps to make a demo of signing up users and |
  logging in and logging out.
  %li There can be one admin user which can be made by rails console by |
  setting admin = 1 for the User in the user model.
  %li The admin user can delete the other user.
  %li Every user can update its information by going on the Setting in |
  navbar menu.
  %li Every user can see all the user by clicking on user after logging |
  in the navbar menu.
  %li The email section validates for valid email address.
  %li The password is stored using a BCrypt hash so it is secure.

app/views/static_pages/contact.html.haml
= provide(:title, 'Contact')
%h1 Contact
%p Contact me by clicking on |
#{ link_to "Email", "mailto:harshdeepkanhai@gmail.com" }. |

app/views/static_pages/help.html.haml
= provide(:title, "Help")
%h1 Help
%p Get help on the Ruby on Rails at the |
#{ link_to "Rails Documentation help page", "http://guides.rubyonrails.org" }. |

app/views/static_pages/home.html.haml
.center.jumbotron
  %h1 Welcome to the User Auth App
  %h2 This is the home page for the User Auth Application
  = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"
= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/'

app/views/users/_form.html.haml
= form_for(@user) do |f|
  = render 'shared/error_messages'

  = f.label :name
  = f.text_field :name, class: 'form-control'

  = f.label :email
  = f.email_field :email, class: 'form-control'

  = f.label :password
  = f.password_field :password, class: 'form-control'

  = f.label :password_confirmation, "Confirmation"
  = f.password_field :password_confirmation, class: 'form-control'

  = f.submit yield(:button_text), class: "btn btn-primary"

app/views/users/_user.html.haml
%li
  = gravatar_for user, size: 50
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    | #{ link_to "delete", user, method: :delete, |
                                 data: { confirm: "You sure?" } } |

app/views/users/edit.html.haml
= provide(:title, 'Edit user')
= provide(:button_text, 'Save changes')
%h1 Update your profile

.row
  .col-md-6.col-md-offset-3
    = render 'form'

    .gravatar_edit
      = gravatar_for @user
      %a(href="http://gravatar.com/emails" target="_blank")change

app/views/users/index.html.haml
= provide(:title, 'All users')
%h1 All users

= will_paginate

%ul.users
  = render @users

= will_paginate

app/views/users/new.html.haml
= provide(:title, 'Sign up')
= provide(:button_text, 'Create my account')
%h1 Sign up

.row
  .col-md-6.col-md-offset-3
    = render 'form'

app/views/users/show.html.haml
= provide(:title, @user.name)
.row
  %aside.col-md-4
    %section.user_info
      %h1
        = gravatar_for @user
        = @user.name